name: bdd_steps
description: BDD test steps for xp1 project.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ">=3.24.0"

dependencies:
  bdd_widget_test: ^2.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  hydrated_bloc: ^10.1.1
  intl: ^0.20.2
  mocktail: ^1.0.4
  shared_preferences: ^2.3.4
  xp1:
    path: ../../

dev_dependencies:
  test: ^1.26.2
  very_good_analysis: ^9.0.0
