include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/firebase_options.dart"
    - "build/**"
    - "coverage/**"
    - "lib/l10n/gen/*"

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  # Custom severity overrides for naming violations
  errors:
    # Make naming violations errors (not warnings)
    non_constant_identifier_names: error
    camel_case_types: error
    constant_identifier_names: error
    file_names: error
    library_names: error
    package_names: error

    # Critical code quality issues
    missing_required_param: error
    missing_return: error
    avoid_dynamic_calls: error

    # Documentation requirement
    public_member_api_docs: error

    # Line length enforcement
    lines_longer_than_80_chars: error

    # Cascade operator consistency
    cascade_invocations: error
    avoid_single_cascade_in_expression_statements: error

    # Ignore invalid_annotation_target errors
    invalid_annotation_target: ignore

# Custom linter rule overrides (only non-default settings)
linter:
  rules:
    # Use relative imports for files within the same package (project style guide)
    # This overrides the very_good_analysis default of true
    always_use_package_imports: false

    # Allow category-based dependency organization instead of strict alphabetical
    # This allows better logical grouping of dependencies
    sort_pub_dependencies: false
