targets:
  $default:
    builders:
      envied_generator|envied:
        options:
          # Override environment file path from CLI using --define
          override: true
        generate_for:
          # Only scan env files - much faster
          - lib/features/env/env_*.dart
      injectable_generator|injectable_builder:
        options:
          auto_register: true
          # Performance: Focus only on DI-related files
          generate_for:
            - lib/core/di/*.dart
            - lib/core/**/app_module.dart
            - lib/**/infrastructure/*.dart
        # Performance: Exclude test and generated files
        enabled: true
      widgetbook_generator|widgetbook_generator_builder:
        options:
          path: widgetbook
        enabled: true
    # Performance: Limit source scanning
    sources:
      include:
        - $package$
        - lib/**
        - widgetbook/** # Include widgetbook folder for stories generation
        - pubspec.yaml
      exclude:
        - test/test/** # Exclude the old nested test folder
        - .dart_tool/**
        - build/**
