targets:
  $default:
    builders:
      envied_generator|envied:
        options:
          # Override environment file path from CLI using --define
          override: true
      injectable_generator|injectable_builder:
        options:
          auto_register: true
          # Focus on lib folder only
          generate_for:
            - lib/**
