name: "Flutter Setup with FVM"
description: "Optimized Flutter setup with FVM, caching, and dependencies"
inputs:
  flutter-version:
    description: "Flutter version to use"
    required: true
    default: "3.35.1"
  cache-key-suffix:
    description: "Additional cache key suffix"
    required: false
    default: ""
  install-deps:
    description: "Install pub dependencies"
    required: false
    default: "true"
  setup-build-runner:
    description: "Setup build_runner caching"
    required: false
    default: "false"
  enable-performance-monitor:
    description: "Enable performance monitoring"
    required: false
    default: "false"
  job-name:
    description: "Name of the job for monitoring"
    required: false
    default: "flutter-setup"

outputs:
  cache-hit:
    description: "Whether cache was hit"
    value: ${{ steps.cache-check.outputs.cache-hit }}
  flutter-path:
    description: "Flutter installation path"
    value: ${{ steps.setup.outputs.flutter-path }}
  duration:
    description: "Job duration in seconds (if monitoring enabled)"
    value: ${{ steps.monitor.outputs.duration }}
  recommendations:
    description: "Performance recommendations (if monitoring enabled)"
    value: ${{ steps.monitor.outputs.recommendations }}

runs:
  using: composite
  steps:
    - name: 🗂️ Cache FVM and Flutter SDK (global)
      id: cache-check
      uses: actions/cache@v4
      with:
        path: |
          ~/.fvm
          ~/.pub-cache
        key: flutter-fvm-${{ inputs.flutter-version }}-${{ runner.os }}-v3${{ inputs.cache-key-suffix }}
        restore-keys: |
          flutter-fvm-${{ inputs.flutter-version }}-${{ runner.os }}-v3
          flutter-fvm-${{ inputs.flutter-version }}-${{ runner.os }}-

    - name: 🔧 Install FVM (if needed)
      shell: bash
      run: |
        # Install FVM if not cached
        if ! command -v fvm &> /dev/null; then
          curl -fsSL https://fvm.app/install.sh | bash
        fi
        export PATH="$HOME/.fvm/bin:$PATH"
        echo "$HOME/.fvm/bin" >> $GITHUB_PATH

    - name: 🔧 Setup Flutter with FVM (optimized)
      id: setup
      shell: bash
      run: |
        # Ensure FVM in PATH
        export PATH="$HOME/.fvm/bin:$PATH"

        # Fast Flutter setup with smart caching
        if [ -d "$HOME/.fvm/versions/${{ inputs.flutter-version }}" ]; then
          echo "✅ Flutter ${{ inputs.flutter-version }} found in cache"
          fvm use ${{ inputs.flutter-version }} --force --skip-setup
        else
          echo "⏬ Installing Flutter ${{ inputs.flutter-version }}"
          fvm install ${{ inputs.flutter-version }} --setup
          fvm use ${{ inputs.flutter-version }} --force
        fi

        # Add Flutter and Dart binaries to PATH (critical fix)
        FLUTTER_BIN_PATH="$HOME/.fvm/versions/${{ inputs.flutter-version }}/bin"
        DART_BIN_PATH="$HOME/.fvm/versions/${{ inputs.flutter-version }}/bin/cache/dart-sdk/bin"

        echo "$FLUTTER_BIN_PATH" >> $GITHUB_PATH
        echo "$DART_BIN_PATH" >> $GITHUB_PATH
        export PATH="$FLUTTER_BIN_PATH:$DART_BIN_PATH:$PATH"

        # Verify both Flutter and Dart are accessible
        if command -v flutter &> /dev/null; then
          echo "✅ Flutter is accessible at: $(which flutter)"
          flutter --version
        else
          echo "❌ Flutter not found in PATH after setup"
          exit 1
        fi

        if command -v dart &> /dev/null; then
          echo "✅ Dart is accessible at: $(which dart)"
          dart --version
        else
          echo "❌ Dart not found in PATH after setup"
          exit 1
        fi

        # Set output
        echo "flutter-path=$HOME/.fvm/versions/${{ inputs.flutter-version }}" >> $GITHUB_OUTPUT

    - name: 🗂️ Cache pub dependencies
      if: inputs.install-deps == 'true'
      uses: actions/cache@v4
      with:
        path: |
          ~/.pub-cache
          .dart_tool/package_config.json
        key: pub-deps-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}-v2
        restore-keys: |
          pub-deps-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}-
          pub-deps-${{ runner.os }}-

    - name: 🗂️ Cache build_runner (if enabled)
      if: inputs.setup-build-runner == 'true'
      uses: actions/cache@v4
      with:
        path: |
          .dart_tool/build
          lib/**/*.g.dart
          lib/**/*.config.dart
        key: build-runner-${{ runner.os }}-${{ hashFiles('**/pubspec.lock', 'build.yaml') }}-${{ hashFiles('lib/**/*.dart', '!lib/**/*.g.dart', '!lib/**/*.config.dart') }}-v3
        restore-keys: |
          build-runner-${{ runner.os }}-${{ hashFiles('**/pubspec.lock', 'build.yaml') }}-
          build-runner-${{ runner.os }}-

    - name: 📦 Install dependencies
      if: inputs.install-deps == 'true'
      shell: bash
      run: |
        # Ensure FVM, Flutter, and Dart are in PATH
        FLUTTER_BIN_PATH="$HOME/.fvm/versions/${{ inputs.flutter-version }}/bin"
        DART_BIN_PATH="$HOME/.fvm/versions/${{ inputs.flutter-version }}/bin/cache/dart-sdk/bin"
        export PATH="$HOME/.fvm/bin:$FLUTTER_BIN_PATH:$DART_BIN_PATH:$PATH"

        # Verify both Flutter and Dart are accessible before running pub get
        if command -v flutter &> /dev/null && command -v dart &> /dev/null; then
          echo "✅ Flutter ready for pub get: $(which flutter)"
          echo "✅ Dart ready for pub get: $(which dart)"
          fvm flutter pub get --suppress-analytics
        else
          echo "❌ Flutter or Dart not accessible for pub get"
          exit 1
        fi

    - name: 📊 Monitor Performance
      id: monitor
      if: inputs.enable-performance-monitor == 'true'
      shell: bash
      run: |
        # Record timing
        end_time=$(date +%s)
        start_time=${GITHUB_JOB_START_TIME:-$(date +%s)}
        duration=$((end_time - start_time))

        echo "duration=$duration" >> $GITHUB_OUTPUT
        echo "⏱️ Job '${{ inputs.job-name }}' completed in ${duration}s"

        # Performance analysis
        recommendations=""
        if [ $duration -gt 300 ]; then
          recommendations="Consider using faster runners or better caching"
        elif [ $duration -gt 180 ]; then
          recommendations="Good performance, minor optimizations possible"
        else
          recommendations="Excellent performance!"
        fi

        echo "recommendations=$recommendations" >> $GITHUB_OUTPUT
        echo "💡 $recommendations"

        # Cache hit analysis
        if [ -f "$RUNNER_TEMP/cache-stats" ]; then
          echo "📊 Cache Performance:"
          cat "$RUNNER_TEMP/cache-stats"
        fi

    - name: 📈 Performance Summary
      if: inputs.enable-performance-monitor == 'true'
      shell: bash
      run: |
        echo "## 🚀 Performance Report for ${{ inputs.job-name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Duration**: ${{ steps.monitor.outputs.duration }}s" >> $GITHUB_STEP_SUMMARY
        echo "- **Recommendation**: ${{ steps.monitor.outputs.recommendations }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Runner**: ${{ runner.os }}-${{ runner.arch }}" >> $GITHUB_STEP_SUMMARY
