import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

// Import will be generated by build_runner
// ignore: unused_import
import 'injection_container.config.dart';

/// Global service locator instance
final GetIt getIt = GetIt.instance;

/// Configures dependency injection for the application
@InjectableInit()
Future<void> configureDependencies() async {
  try {
    getIt.init();
  } catch (e) {
    // Basic error handling for DI initialization
    throw Exception('Failed to initialize dependency injection: $e');
  }
}
